#include <stdio.h>

#define DFDR "/usr/bin"

#include "struct.h"

struct exec_list *root;

int internal_tst(treeroot)
struct exec_list *treeroot;
{
FILE *fp, *openfile();
char *filename, *filename2, *filename3, *tempnam(), *getcwd();
char *directory;

   root = treeroot;

   filename = tempnam(getcwd((char *)NULL, 80), "IVT-");
   filename2 = tempnam(getcwd((char *)NULL, 80), "IVT-");
   filename3 = tempnam(getcwd((char *)NULL, 80), "IVT-");
   directory = tempnam(getcwd((char *)NULL, 80), "IVT-");
   fp = openfile(filename, "w+");
   if (fp != NULL) {
      fprintf(fp, "FILE NAMES GENERATED BY tempnam are:       %s\n", filename);
      fprintf(fp, "                                           %s\n", filename2);
      fprintf(fp, "                                           %s\n", filename3);
      fprintf(fp, "DIRECTORY NAMES GENERATED BY tempnam are:  %s\n", directory);
      fprintf(fp, "This is a test file for the installation\n");
      fprintf(fp, "test IVT.  This preliminary stuff is just to\n");
      fprintf(fp, "create the file for commands tests\n\n");
      fclose(fp);
   }
   dotests(filename, filename2, filename3, directory);
}

int dotests(filename, filename2, filename3, directory)
char *filename, *filename2, *filename3, *directory;
{
char cmdline[81];
/*
Supply a pathname to the command
*/

   clearline(cmdline);
   cctst("/bin",filename, cmdline);
   clearline(cmdline);
   f77tst(filename, cmdline);
   clearline(cmdline);
   lognametst(filename, cmdline);
   clearline(cmdline);
   unametst(filename, cmdline);
   clearline(cmdline);
   ttytst(filename, cmdline);
   clearline(cmdline);
   envtst(filename, cmdline);
   clearline(cmdline);
   datetst(filename, cmdline);
   clearline(cmdline);
   echotst(filename, cmdline);
   clearline(cmdline);
   copytst(filename, cmdline, filename2);
   clearline(cmdline);
   greptst(filename, cmdline, filename2);
   clearline(cmdline);
   difftst(filename, cmdline, filename2, filename3);
   clearline(cmdline);
   lstst(filename, cmdline);
   clearline(cmdline);
   wctst(filename, cmdline, filename2);
   clearline(cmdline);
   synctst(cmdline);
   clearline(cmdline);
   cdtst(cmdline);
   clearline(cmdline);
   filetst(filename, cmdline);
   clearline(cmdline);
   dirnametst(filename, cmdline);
   clearline(cmdline);
   basenametst(filename, cmdline);
   clearline(cmdline);
   whotst(filename, cmdline);
   clearline(cmdline);
   cattst(filename, cmdline, filename3);
   clearline(cmdline);
   whattst(filename, cmdline);
   clearline(cmdline);
   odtst(filename, cmdline, filename3);
   clearline(cmdline);
   dftst(filename, cmdline);
   clearline(cmdline);
   dutst(filename, cmdline);
   clearline(cmdline);
   pstst(filename, cmdline);
   clearline(cmdline);
   headtst(filename, cmdline, filename2);
   clearline(cmdline);
   tailtst(filename, cmdline, filename2);
   clearline(cmdline);
   mkdirtst(directory, cmdline);
   clearline(cmdline);
   rmdirtst(directory, cmdline);
   clearline(cmdline);
   rmtst(filename, cmdline, filename2, filename3);
}

int clearline(cmdline)
char *cmdline;
{
int i;

   for (i = 0; i < 81; i++)
      cmdline[i] = '\0';
}

int cmdfailed(cmdline, cmdname, err)
char *cmdline, *cmdname;
int err;
{
struct exec_list *lognode, *searchtreecmd();

   printf("COMMAND FAILED:  %s\n", cmdname);
   printf("COMMAND LINE:    %s\n\n", cmdline);
}

int datetst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"date >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "date", err);
}

int echotst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"echo this is an echo test >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "echo", err);
}

int copytst(filename, cmdline, filename2)
char *filename, *cmdline, *filename2;
{
int err = 0;

   sprintf(cmdline,"cp %s %s", filename, filename2);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "cp", err);
}

int greptst(filename, cmdline, filename2)
char *filename, *cmdline, *filename2;
{
int err = 0;

   sprintf(cmdline,"grep echo %s >> %s", filename, filename2);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "grep", err);
}

int difftst(filename, cmdline, filename2, filename3)
char *filename, *cmdline, *filename2, *filename3;
{
union {
   struct {
#ifdef CRAY
      unsigned unused :48, sherr:8, unused2:8;
#else
      unsigned unused :16, sherr:8, unused2:8;
#endif
   } err;
   int retval;
} errstruct;

   errstruct.retval = 0;
   sprintf(cmdline,"diff %s %s >> %s", filename, filename2, filename3);
   errstruct.retval = system(cmdline);
   if (errstruct.err.sherr != 1)
      cmdfailed(cmdline, "diff", errstruct.retval);
}

int lstst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"ls -l >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "ls", err);
}

int wctst(filename, cmdline, filename2)
char *filename, *cmdline, *filename2;
{
int err = 0;

   sprintf(cmdline,"wc %s >> %s", filename, filename2);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "wc", err);
}
int ttytst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"tty >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "tty", err);
}
int lognametst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"logname >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "logname", err);
}
int unametst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"uname -a >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "uname", err);
}
int envtst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"env >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "env", err);
}
int synctst(cmdline)
char *cmdline;
{
int err = 0;

   sprintf(cmdline,"sync");
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "sync", err);
}
int cdtst(cmdline)
char *cmdline;
{
int err = 0;

   sprintf(cmdline,"cd .");
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "cd", err);
}
int filetst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"file %s >> %s", filename, filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "file", err);
}
int dirnametst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"dirname %s >> %s", filename, filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "dirname", err);
}
int basenametst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"basename %s >> %s", filename, filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "basename", err);
}
int whotst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"who >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "who", err);
}
int cattst(filename, cmdline, filename3)
char *filename, *cmdline, *filename3;
{
int err = 0;

   sprintf(cmdline,"cat %s >> %s", filename3, filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "cat", err);
}
int whattst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"what /bin/cc >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "what", err);
}
int odtst(filename, cmdline, filename3)
char *filename, *cmdline, *filename3;
{
int err = 0;

   sprintf(cmdline,"od %s >> %s", filename3, filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "od", err);
}
int dftst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"df >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "df", err);
}
int dutst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"du >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "du", err);
}
int pstst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"ps >> %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "ps", err);
}
int headtst(filename, cmdline, filename2)
char *filename, *cmdline, *filename2;
{
int err = 0;

   sprintf(cmdline,"head -5 %s >> %s", filename, filename2);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "head", err);
}
int tailtst(filename, cmdline, filename2)
char *filename, *cmdline, *filename2;
{
int err = 0;

   sprintf(cmdline,"tail -5 %s >> %s", filename, filename2);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "tail", err);
}
int mkdirtst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"mkdir %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "mkdir", err);
}
int rmdirtst(filename, cmdline)
char *filename, *cmdline;
{
int err = 0;

   sprintf(cmdline,"rmdir %s", filename);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "rmdir", err);
}
int rmtst(filename, cmdline, filename2, filename3)
char *filename, *cmdline, *filename2, *filename3;
{
int err = 0;

   sprintf(cmdline,"rm %s %s %s", filename, filename2, filename3);
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "rm", err);
}
int cctst(pathname, filename, cmdline)
char *pathname, *filename, *cmdline;
{
FILE *fp;
int err = 0;

   fp = openfile("hello.c", "w+");
   if (fp != NULL) {
      fprintf(fp, "main()\n{\n");
      fprintf(fp, "   printf(\"hello world\\n\")\;\n   exit(0)\;\n}\n");
      fclose(fp);
      sprintf(cmdline,"%s/cc -c hello.c", pathname);
      err = system(cmdline);
      if (err != 0)
         cmdfailed(cmdline, "cc", err);
      else {
         clearline(cmdline);
         err = segldrtst("hello.o", cmdline, "-lc");
         if (err != 0)
            return;
         clearline(cmdline);
         sprintf(cmdline, "hello >> %s", filename);
         err = system(cmdline);
         if (err != 0)
            cmdfailed(cmdline, "cc executable", err);
         else {
            unlink("hello.c");
            unlink("hello.o");
            unlink("hello");
         }
      }
   }
}
int f77tst(filename, cmdline)
char *filename, *cmdline;
{
FILE *fp;
int err = 0;

   fp = openfile("hello.f", "w+");
   if (fp != NULL) {
      fprintf(fp, "      PROGRAM HELLO\n");
      fprintf(fp, "      PRINT*,\"HELLO WORLD\"\n");
      fprintf(fp, "      END\n");
      fclose(fp);
#ifdef CRAY
      sprintf(cmdline,"cft77 hello.f");
#else
      sprintf(cmdline,"f77 -c hello.f");
#endif
      err = system(cmdline);
      if (err != 0)
         cmdfailed(cmdline, "cft77", err);
      else {
         clearline(cmdline);
#ifdef CRAY
         err = segldrtst("hello.o", cmdline, "");
#else
         err = segldrtst("hello.o", cmdline, "-lF77 -lc");
#endif
         if (err != 0)
            return;
         clearline(cmdline);
         sprintf(cmdline, "hello >> %s", filename);
         err = system(cmdline);
         if (err != 0)
            cmdfailed(cmdline, "cft77 executable", err);
         else {
            unlink("hello.f");
            unlink("hello.o");
            unlink("hello");
         }
      }
   }
}
int segldrtst(filename, cmdline, libstr)
char *filename, *cmdline, *libstr;
{
int err = 0;

#ifdef CRAY
   sprintf(cmdline, "segldr -o hello %s %s", filename, libstr);
#else
   sprintf(cmdline,"ld -e start -o hello /usr/lang/SC0.0/crt0.o %s %s",
           filename, libstr);
#endif
   err = system(cmdline);
   if (err != 0)
      cmdfailed(cmdline, "segldr", err);
   return(err);
}
