
package velocity;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VelocityService", targetNamespace = "urn:/velocity", wsdlLocation = "http://testbed6-8.bigdatalab.ibm.com/vivisimo/cgi-bin/velocity?v.app=api-soap&use-types=true&wsdl=1")
public class VelocityService
    extends Service
{

    private final static URL VELOCITYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(velocity.VelocityService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = velocity.VelocityService.class.getResource(".");
            url = new URL(baseUrl, "http://testbed6-8.bigdatalab.ibm.com/vivisimo/cgi-bin/velocity?v.app=api-soap&use-types=true&wsdl=1");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://testbed6-8.bigdatalab.ibm.com/vivisimo/cgi-bin/velocity?v.app=api-soap&use-types=true&wsdl=1', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VELOCITYSERVICE_WSDL_LOCATION = url;
    }

    public VelocityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VelocityService() {
        super(VELOCITYSERVICE_WSDL_LOCATION, new QName("urn:/velocity", "VelocityService"));
    }

    /**
     * 
     * @return
     *     returns VelocityPort
     */
    @WebEndpoint(name = "VelocityPort")
    public VelocityPort getVelocityPort() {
        return super.getPort(new QName("urn:/velocity", "VelocityPort"), VelocityPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VelocityPort
     */
    @WebEndpoint(name = "VelocityPort")
    public VelocityPort getVelocityPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:/velocity", "VelocityPort"), VelocityPort.class, features);
    }

}
