#!/bin/bash

estat=99

if [ -f querywork/idxall-1.index ]; then

   cat querywork/idxall-1.index | grep '^(word' | cut -d , -f 2 | tr -d ') \n\t' | iconv -f utf-8 -t utf-16le | od -t x2 --width=2 | cut -d ' ' -f 2 -s | sort | uniq > querywork/chars-normal

   if [ -f querywork/chars-normal ]; then
      diff querywork/chars-normal compare_files/index_good
      estat=$?
   fi
fi

exit $estat
