#!/bin/bash

x=`cat whodo`
touch junkfile

for y in $x;do
   echo "#######" >> junkfile
   echo "#######" >> junkfile
   echo "=== $y" >> junkfile
   xml fo /winexport/samba_test_data/samba-2/doc/dmoz/dmoz/$y | grep -i "Hamilton" >> junkfile
done
