require 'rspec/core/rake_task'
require File.dirname(__FILE__) + '/helpers/spec_helper'

single_test = ENV['TEST']

rspec_formatter_defaults = Array.new
rspec_formatter_defaults << '--color'
# report_formatter_path = `gem which -q "selenium/rspec/reporting/selenium_test_report_formatter"`.chomp
# rspec_formatter_defaults << "--require '#{report_formatter_path}'" # selenium-client 1.2.18 is requiring 'spec' instead of 'rspec'
rspec_formatter_defaults << "--format=progress"

task :default => :test

desc "Run all tests in specs directory"
task :test => [:'test:spec_tests']

namespace :test do
  @verbose = (ENV['VERBOSE']) ? true : false
  @quiet = !@verbose

  if single_test
    rspec_formatter_defaults << "--example \"#{single_test}\""
  end

  desc ""
  RSpec::Core::RakeTask.new('spec_tests') do |t|
    t.pattern = "**specs/*spec.rb"
    t.rspec_opts = rspec_formatter_defaults
    t.fail_on_error = false
  end
end

desc "Check whether you installed all dependencies and your environment is OK."
task :sanity_check do
  puts <<-EOS

 Congratulations, your environment is set properly.

 Run 'rake help' for help!

  EOS

  puts " Your notable environment variables are: \n"
  puts "    ENV_TOKEN=#{ENV['ENV_TOKEN']}" unless ENV['ENV_TOKEN'].nil?
  puts "    SELENIUM_APPLICATION_HOST=#{ENV['SELENIUM_APPLICATION_HOST']}"
end

desc "Start Selenium Server in multi-window mode"
task :'rc:start:mw' do
  puts '**Selenium Server Started in multi-window mode'
  `java -jar selenium_server/selenium-server.jar -browserSessionReuse -trustAllSSLCertificates`
end

desc "Start Selenium Server in single-window mode"
task :'rc:start' do
  puts '**Selenium Server Started in single-window mode'
  `java -jar selenium_server/selenium-server.jar -singlewindow -browserSessionReuse`
end

desc "Show test help"
task :help do
  puts <<-EOS

  To see all commands:

      $ rake -T

  To start the selenium server in "single window" mode:

      $ rake rc:start

  To run all tests:

      $ rake test

  To run a single spec file:

      $ rake SPEC=examples/browser_spec.rb

  To run a single test within a spec (you need to use the whole "should" string):

      $ rake SPEC=examples/browser_spec.rb TEST="can find Selenium"

  To run a line number (may just be one test or an entire context):

      $ rake SPEC=example/browser_spec.rb:9
  EOS
end