#!/usr/bin/python

#
#   Test of the api
#   This test is for search-collection-create and
#   search-collection-delete.  It creates and deletes
#   a number of collections using different variations
#   of characters.
#

import sys, time, cgi_interface 

def test_function(xx=None, vfunc=None):

   if ( vfunc == None ):
      return

   if ( xx.TENV.targetos == "windows" ):
      httpcmd = "/vivisimo/cgi-bin/velocity.exe"
   else:
      httpcmd = "/vivisimo/cgi-bin/velocity"

   dumpit = ''.join(['querywork/', vfunc, '.wazzat'])

   appname = 'api-rest'

   httpstring = ''.join(['v.app=', appname,
                         '&v.function=', vfunc])

   err = xx.HTTP.doget(tocmd=httpcmd, argstring=httpstring, dumpfile=dumpit)

   return



if __name__ == "__main__":

   ss_start = ss_stop = 0
   maxcount = 10
   collection_name = "letters"

   print "api-ss-start-stop-1:  search-collection-create/search-collection-delete"
   xx = cgi_interface.CGIINTERFACE()
   if ( xx.collection_exists(collection_name) == 0 ):
      print "DOES NOT EXIST"
   else:
      print "EXISTS"

   sys.exit(1)
